### DISCUSSION TITLE
ESPHome switch component not found during compilation

### DISCUSSION THREAD

**Discussion by ChristopheHD** [philippemezzadri/frisquet-esphome#11] [Q&A] [answered]
Hello,
This is my first try on ESPHome and I fail to compile this component. The error log indicates that ESPHome switch component is not found. Did I miss something in the configuration file ?
Logs:
```
INFO ESPHome 2025.2.2
INFO Reading configuration /config/esphome/frisquet.yaml...
WARNING GPIO45 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Generating C++ source...
INFO Compiling app...
Processing frisquet (board: esp32-s3-devkitc-1; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32S3 240MHz, 320KB RAM, 8MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5 
 - toolchain-xtensa-esp32s3 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- WiFi @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- Update @ 2.0.0
|-- noise-c @ 0.1.6
Compiling .pioenvs/frisquet/src/esphome/components/frisquet_boiler/frisquet_boiler.cpp.o
Compiling .pioenvs/frisquet/src/esphome/components/frisquet_boiler/sensor/frisquet_boiler_sensor.cpp.o
Compiling .pioenvs/frisquet/src/esphome/components/logger/logger_esp8266.cpp.o
Compiling .pioenvs/frisquet/src/esphome/components/logger/logger_host.cpp.o
Compiling .pioenvs/frisquet/src/esphome/components/logger/logger_libretiny.cpp.o
Compiling .pioenvs/frisquet/src/esphome/components/logger/logger_rp2040.cpp.o
Compiling .pioenvs/frisquet/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/frisquet/src/esphome/components/mdns/mdns_component.cpp.o
In file included from src/esphome/components/frisquet_boiler/sensor/frisquet_boiler_sensor.h:3,
                 from src/esphome/components/frisquet_boiler/sensor/frisquet_boiler_sensor.cpp:1:
src/esphome/components/frisquet_boiler/sensor/../frisquet_boiler.h:4:10: fatal error: esphome/components/switch/switch.h: No such file or directory
 #include "esphome/components/switch/switch.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/esphome/components/frisquet_boiler/frisquet_boiler.cpp:1:
src/esphome/components/frisquet_boiler/frisquet_boiler.h:4:10: fatal error: esphome/components/switch/switch.h: No such file or directory
 #include "esphome/components/switch/switch.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
compilation terminated.
*** [.pioenvs/frisquet/src/esphome/components/frisquet_boiler/sensor/frisquet_boiler_sensor.cpp.o] Error 1
*** [.pioenvs/frisquet/src/esphome/components/frisquet_boiler/frisquet_boiler.cpp.o] Error 1
========================= [FAILED] Took 11.62 seconds =========================
```

And this is my configuration file:
```
esphome:
  name: frisquet
  friendly_name: Frisquet

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "encryption_key"

ota:
  - platform: esphome
    password: "ota_password"

ethernet:
  type: W5500
  clk_pin: GPIO48
  mosi_pin: GPIO21
  miso_pin: GPIO47
  cs_pin: GPIO45
  interrupt_pin: GPIO14
  clock_speed: 30Mhz

external_components:
  - source: github://philippemezzadri/frisquet-esphome

output:
  - platform: frisquet_boiler
    id: chaudiere
    pin: 18
    boiler_id: 9AD6

sensor:
  - platform: frisquet_boiler
    name: "Température eau chaudière"
    type: FLOWTEMP
  - platform: frisquet_boiler
    name: "Puissance chaudière"
    type: SETPOINT
```

**Comment by philippemezzadri** [comment, marked as answer]
Hello @ChristopheHD 

Thank you for the interest you show for this project.
There is a lot missing in your yaml file but this should not be a problem for the compilation and I don't see why you get the error 
```fatal error: esphome/components/switch/switch.h: No such file or directory```

Anyway, try to add the following and see if this helps with the compilation:

```yaml
switch:
  - platform: frisquet_boiler
    test:
      name: "mode Test"
    pair:
      name: "mode Configuration"
```

Tell how it goes with this.

In any case, defining the `frisquet_boiler` output component is not enough, you need a `climate` component as well to control the output. I recommend using the `heat_curve_climate` component from the same project but you could also use the `pid` component from esphome. Everything is explained in the project documentation.  Have a look also at [this](https://github.com/philippemezzadri/frisquet-esphome/blob/main/boiler.yaml) for a complete yaml config file.

**Reply by ChristopheHD** [reply]
Thank you very much for the quick reply !
I successfully compiled by adding the switch you mentioned.

I chose to not use the heat_curve_climate component. My idea is to expose in Home Assistant the output entity so Home Assistant can choose the right output. I have the feeling that puting the thermostat logic inside the ESP32 will put limitation on the thermostat itself.

**Reply by philippemezzadri** [reply]
Interesting to see that if there is no switch defined in the yaml file, the `switch.h` file is not accessible for compilation. The switches should be optional normally. I need to look at this and find a fix.

If you want to control the output from Home Assistant, you may need to add the following in your yaml file:

```yaml
api:
  actions:
    - action: set_boiler_setpoint
      variables:
        setpoint: int
      then:
        - output.set_level:
            id: boiler_cmd
            level: !lambda 'return setpoint / 100.0;'
```
